name: Check PR Conflicts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "BRANCH_NAME=${BRANCH_NAME}"
          API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?state=open&base=${BRANCH_NAME}"
          echo "API_URL=$API_URL"
          PR_NUMS=(`curl -s -H "Authorization: token $GH_TOKEN" "$API_URL"|jq -r '.[] | .number'`)
          for PR_NUM in "${PR_NUMS[@]}"; do
            echo "PR_NUM=$PR_NUM"
            curl -i -s -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUM}" > /dev/null
            sleep 1
          done
          sleep 10
          echo '.....'
          for PR_NUM in "${PR_NUMS[@]}"; do
            echo "PR_NUM=$PR_NUM"
            TITLE=''
            USER=''
            curl -s -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUM}" > out.json
            TITLE=`cat out.json | jq -r 'select(.mergeable_state == "dirty")|.title'`
            USER=`cat out.json | jq -r 'select(.mergeable_state == "dirty")|.user.login'`
            echo "PR_NUM=$PR_NUM USER=$USER TITLE=$TITLE"
            if [[ ! -z $TITLE ]]; then
              LINK="https://github.com/${GITHUB_REPOSITORY}/pull/${PR_NUM}"
              WEBHOOK_URL="https://discord.com/api/webhooks/1237780527822671944/x28KR9UF6wWJ_yY6Mb2bmnp-EQONG-F2M4Pf5_FXDOXlud0d9HMNiTmvs6yX2gXFGFAs"
              curl -H "Content-Type: application/json" -d '{"username": "GitHub-PR-Checks", "content": "Repo: '"${GITHUB_REPOSITORY}"'\nPR: PullRequest-'"${PR_NUM}"' Merge Conflict\nLink: '"${LINK}"'\nTitle: '"${TITLE}"'\nAuthor: '"${USER}"'"}' $WEBHOOK_URL
            fi
            #cat out.json
            rm out.json
            sleep 1
          done  
        shell: bash
