name: Check PR Conflicts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "BRANCH_NAME=${GITHUB_REF##*/}"
          API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?state=open&base=${BRANCH_NAME}"
          echo "API_URL=$API_URL"
          curl -i -s -H "Authorization: token $GH_TOKEN" "$API_URL"
          curl -i -s -H "Authorization: token $GH_TOKEN" "$API_URL" | jq -r '.[] | select(.mergeable_state == "dirty") | "\(.number) \(.title) by \(.user.login)"'
        shell: bash
